FROM openjdk:17-jdk-slim

WORKDIR /app

COPY /ShopmeWebParent/ShopmeBackEnd/target/*.jar .

ENV MYSQL_DB_HOST = $MYSQL_DB_HOST
ENV MYSQL_DB_PORT = $MYSQL_DB_PORT
ENV MYSQL_DB_USERNAME = $MYSQL_DB_USERNAME
ENV MYSQL_DB_PASSWORD = $MYSQL_DB_PASSWORD

EXPOSE 8080

CMD ["java", "-jar", "ShopmeBackEnd-1.0-SNAPSHOT.jar"]
